import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css'
import NavBar from './components/navbar'
import page_layout from './layout.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Restaurantly',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="container">
          <div className="row">
            <div className="col-md"></div>
            <NavBar />
          </div>
          <div className="row">
            <div className="col-md">{children}</div>

          </div>

        </div>
      </body>
    </html>
  )
}
